server.port=8085
spring.application.name=maintenance-service
spring.config.import=optional:configserver:${SPRING_CONFIG_SERVER_URI:http://localhost:8888}
eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/assets_maintenance_db
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false
jwt.secret=${JWT_SECRET:your_super_secret_key_that_should_be_at_least_256_bits_long_for_HS256_algorithm_in_production}
feign.asset-service.url=${ASSET_SERVICE_URL:http://localhost:8082}
management.endpoints.web.exposure.include=health,info
